### ISSUE TITLE
Upload to 4TU and Zenodo fails

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/jupyter-fairly#70]
- Attempting to upload to **4TU** fails with the following:
```python
[W 2023-03-19 23:50:58.222 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/Documents/devel/jupyter-fairly/jupyter_fairly/jupyter_fairly/handlers.py", line 253, in post
        local_dataset.upload(client)
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/dataset/local.py", line 354, in upload
        dataset = client.create_dataset(self.metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/__init__.py", line 292, in create_dataset
        id = self._create_dataset(metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/figshare.py", line 753, in _create_dataset
        result, _ = self._request("account/articles", "POST", data={"title": metadata.get("title", "")})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/__init__.py", line 355, in _request
        response.raise_for_status()
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.figshare.com/v2/account/articles

```

- Attempting to upload to **Zenodo** fails with the following: 
```python
[W 2023-03-19 23:54:16.875 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/Documents/devel/jupyter-fairly/jupyter_fairly/jupyter_fairly/handlers.py", line 253, in post
        local_dataset.upload(client)
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/dataset/local.py", line 354, in upload
        dataset = client.create_dataset(self.metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/__init__.py", line 292, in create_dataset
        id = self._create_dataset(metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/zenodo.py", line 291, in _create_dataset
        result, _ = self._request("deposit/depositions", "POST", data={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/fairly/client/__init__.py", line 355, in _request
        response.raise_for_status()
      File "/home/manuel/miniconda3/envs/jupyterfairly/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://zenodo.org/api/deposit/depositions

```

**Comment by manuGil** [comment]
@girgink  Can we check if this issue also happens withing fairly?

**Comment by manuGil** [comment]
The Issue with Zenodo was about setting the right permission when creating a personal token. The issue with 4TU was moved to a new issue #73
